# Generated by Django 4.0 on 2022-01-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(default='author', max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('summary', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=100000)),
            ],
        ),
    ]
